version: '2'
services:

#---------------------------------------------
#                 Nats config
#---------------------------------------------
  nats:
    build:
      context: ./docker/nats
    expose:
      - 4222
    restart: on-failure
    volumes:
      - ${NATS_HOST_LOG_PATH}:/var/log
    networks:
      - gameof3

#---------------------------------------------
#            Game backend config
#---------------------------------------------
  game:
    build:
      context: ./docker/backend
      args:
        - WORKDIR=${BACKEND_PATH}
    volumes:
      - ./backend:${BACKEND_PATH}
    networks:
      - gameof3
    depends_on:
      - nats

#---------------------------------------------
#            Game client config
#---------------------------------------------
  client:
    build:
      context: ./docker/client
      args:
        - WORKDIR=${CLIENT_PATH}
    ports:
      - "${CLIENT_PORT}:3000"
    volumes:
      - ./client:${CLIENT_PATH}
    networks:
      - gameof3
    depends_on:
      - nats
      - game

networks:
  gameof3:
    driver: "bridge"